name: Security Pipeline
on:
  push:
    branches:
      - build/security
      - main
  pull_request:
    branches: [ main ]
  workflow_run:
    workflows: [ "Test" ]
    types:
      - completed
jobs:
  codeql:
    name: Static Code Analysis (SAST)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v4
        with:
          languages: java

      - name: Build java code
        run: mvn -B -DskipTests package

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v4


  dependency-check:
    name: Dependency Vulnerability Scan (SCA)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Dependency Check Scan
        run: mvn org.owasp:dependency-check-maven:check -Dnvd.api.key=${{ secrets.NVD_API_KEY }}

      - name: Upload Dependency Check Report
        uses: actions/upload-artifact@v6
        with:
          name: dependency-check-report
          path: target/dependency-check-report.html

  sbom:
    name: SBOM & Vulnerability Scan
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Generate SBOM
        uses: anchore/sbom-action@latest
        with:
          artifact-name: sbom.spdx
          upload-artifact: true
      - name: Scan SBOM for Vulnerabilities
        uses: anchore/scan-action@v7
        with:
          sbom: sbom.spdx.json

      - name: Upload SBOM artifact
        uses: actions/upload-artifact@v6
        with:
          name: sbom
          path: sbom.spdx.json